#pragma once

#define LAYER_STATE_8BIT
#define ENABLE_COMPILE_KEYCODE

#define TAPPING_TERM 200
#define TAPPING_TERM_PER_KEY
#define QUICK_TAP_TERM 0

#define EXTRA_LONG_COMBOS
#define COMBO_TERM 50
#define COMBO_MUST_HOLD_MODS
#define COMBO_HOLD_TERM 100
#define COMBO_SHOULD_TRIGGER

#define CAPS_WORD_IDLE_TIMEOUT 3000
#define NUM_WORD_IDLE_TIMEOUT 3000
