#pragma once

#define ENABLE_COMPILE_KEYCODE
#define LAYER_STATE_ON_8_BIT
#undef LOCKING_SUPPORT_ENABLE
#undef LOCKING_RESYNC_ENABLE

#define TAPPING_TERM 200

#define COMBO_TERM 75
#define COMBO_HOLD_TERM 150
#define COMBO_MUST_HOLD_MODS

#define TAPPING_TERM_PER_KEY
#define PERMISSIVE_HOLD_PER_KEY
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY
